from dataclasses import dataclass, field
from datetime import datetime

from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import ConfigDict, Field

from openhound_okta.graph import OktaNode, OktaNodeProperties
from openhound_okta.kinds import edges as ek, nodes as nk
from openhound_okta.main import app


@dataclass
class ApiServiceProperties(OktaNodeProperties):
    """Properties for the Okta_ApiServiceIntegration node"""

    app_type: str
    created_at: datetime
    oauth_scopes: list[str] | None = None
    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )


@app.asset(
    description="Okta API service integration asset",
    node=NodeDef(
        icon="robot",
        kind=nk.INTEGRATION,
        description="Okta API service integration node",
        properties=ApiServiceProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.ORG,
            end=nk.INTEGRATION,
            kind=ek.CONTAINS,
            description="Organization contains API service integration",
            traversable=False,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.INTEGRATION,
            kind=ek.CREATOR_OF,
            description="User created the API service integration",
            traversable=True,
        ),
    ],
)
class ApiService(BaseAsset):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    type: str
    name: str
    created_at: datetime = Field(alias="createdAt")
    created_by: str = Field(alias="createdBy")
    config_guide_url: str = Field(alias="configGuideUrl")
    granted_scopes: list[str] = Field(alias="grantedScopes")

    @property
    def as_node(self):
        return OktaNode(
            kinds=[nk.INTEGRATION],
            properties=ApiServiceProperties(
                tenant=self._lookup.org_id(),
                id=self.id,
                name=self.name,
                displayname=self.name,
                app_type=self.type,
                created_at=self.created_at,
                oauth_scopes=self.granted_scopes,
                environmentid=self._lookup.org_id(),
            ),
        )

    @property
    def _contains_edges(self):
        yield Edge(
            kind=ek.CONTAINS,
            start=EdgePath(value=self._lookup.org_id(), match_by="id"),
            end=EdgePath(value=self.id, match_by="id"),
            properties=EdgeProperties(traversable=False),
        )

    @property
    def _creator_of_edges(self):
        if self.created_by:
            yield Edge(
                kind=ek.CREATOR_OF,
                start=EdgePath(value=self.created_by, match_by="id"),
                end=EdgePath(value=self.id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        yield from self._contains_edges
        yield from self._creator_of_edges
