from pydantic import BaseModel, ConfigDict

BUILT_IN_PERMISSIONS = {
    "API_ACCESS_MGMT_ADMIN": [
        "okta.authzServers.manage",
        "okta.authzServers.read",
        "okta.profileMappings.manage",
        "okta.profileMappings.read",
        "okta.users.read",
        "okta.userTypes.read",
        "okta.groups.read",
        "okta.apps.manage",
        "okta.apps.read",
        "okta.apps.assignment.manage",
        "okta.users.appAssignment.manage",
        "okta.groups.appAssignment.manage",
        "okta.apps.clientCredentials.read",
        "okta.realms.read",
    ],
    "APP_ADMIN": [
        "okta.apps.manage",
        "okta.apps.read",
        "okta.apps.assignment.manage",
        "okta.apps.clientCredentials.read",
        "okta.users.appAssignment.manage",
        "okta.groups.appAssignment.manage",
        "okta.policies.manage",
        "okta.policies.read",
        "okta.users.read",
        "okta.groups.read",
        "okta.users.userprofile.manage",
        "okta.users.userprofile.read",
        "okta.profilesources.import.run",
        "okta.agents.register",
        "okta.realms.read",
    ],
    "GROUP_MEMBERSHIP_ADMIN": [
        "okta.users.read",
        "okta.groups.read",
        "okta.groups.members.manage",
        "okta.users.groupMembership.manage",
        "okta.groups.manage",
        "okta.users.apitokens.read",
        "okta.users.apitokens.manage",
        "okta.users.apitokens.clear",
        "okta.realms.read",
    ],
    "HELP_DESK_ADMIN": [
        "okta.users.read",
        "okta.users.lifecycle.clearSessions",
        "okta.users.credentials.resetPassword",
        "okta.users.credentials.resetFactors",
        "okta.users.risk.manage",
        "okta.groups.read",
        "okta.users.apitokens.clear",
        "okta.realms.read",
    ],
    "MOBILE_ADMIN": [
        "okta.devices.read",
        "okta.devices.manage",
        "okta.devices.lifecycle.manage",
        "okta.policies.read",
        "okta.policies.manage",
        "okta.users.read",
        "okta.groups.read",
        "okta.apps.read",
        "okta.logs.read",
        "okta.users.apitokens.read",
        "okta.agents.register",
        "okta.realms.read",
    ],
    "ORG_ADMIN": [
        "okta.reports.read",
        "okta.customizations.read",
        "okta.customizations.manage",
        "okta.logs.read",
        "okta.authzServers.read",
        "okta.authzServers.manage",
        "okta.users.read",
        "okta.users.create",
        "okta.users.manage",
        "okta.users.lifecycle.manage",
        "okta.users.lifecycle.clearSessions",
        "okta.users.credentials.manage",
        "okta.users.risk.manage",
        "okta.groups.read",
        "okta.groups.create",
        "okta.groups.manage",
        "okta.groups.members.manage",
        "okta.policies.read",
        "okta.devices.read",
        "okta.devices.manage",
        "okta.eventhooks.read",
        "okta.eventhooks.manage",
        "okta.inlinehooks.read",
        "okta.inlinehooks.manage",
        "okta.identityProviders.read",
        "okta.identityProviders.manage",
        "okta.agents.register",
        "okta.users.apitokens.manage",
        "okta.users.apitokens.read",
        "okta.users.apitokens.clear",
        "okta.realms.read",
        "okta.realms.manage",
        "okta.workflows.read",
        "okta.support.cases.manage",
    ],
    "READ_ONLY_ADMIN": [
        "okta.reports.read",
        "okta.customizations.read",
        "okta.authzServers.read",
        "okta.logs.read",
        "okta.devices.read",
        "okta.users.read",
        "okta.users.risk.read",
        "okta.userTypes.read",
        "okta.groups.read",
        "okta.apps.read",
        "okta.policies.read",
        "okta.eventhooks.read",
        "okta.inlinehooks.read",
        "okta.agents.register",
        "okta.users.apitokens.manage",
        "okta.users.apitokens.read",
        "okta.users.apitokens.clear",
        "okta.apps.clientCredentials.read",
        "okta.workflows.read",
        "okta.realms.read",
    ],
    "REPORT_ADMIN": ["okta.reports.read", "okta.logs.read"],
    "SUPER_ADMIN": ["*"],
    "USER_ADMIN": [
        "okta.users.read",
        "okta.users.create",
        "okta.users.lifecycle.delete",
        "okta.users.lifecycle.suspend",
        "okta.users.lifecycle.deactivate",
        "okta.users.lifecycle.activate",
        "okta.users.manage",
        "okta.users.lifecycle.clearSessions",
        "okta.users.userprofile.manage",
        "okta.users.credentials.resetPassword",
        "okta.users.credentials.resetFactors",
        "okta.users.risk.manage",
        "okta.groups.read",
        "okta.groups.members.manage",
        "okta.users.groupMembership.manage",
        "okta.groups.manage",
    ],
    "API_ADMIN": [
        "okta.users.apitokens.manage",
        "okta.users.apitokens.read",
        "okta.users.apitokens.clear",
    ],
    "ACCESS_CERTIFICATIONS_ADMIN": [
        "okta.governance.accessCertifications.manage",
        "okta.governance.collections.read",
        "okta.apps.read",
        "okta.users.read",
        "okta.groups.read",
    ],
    "ACCESS_REQUEST_ADMIN": [
        "okta.governance.accessRequests.manage",
        "okta.apps.assignment.manage",
        "okta.governance.collections.read",
        "okta.groups.appAssignment.manage",
        "okta.apps.manageFirstPartyApps",
        "okta.apps.manage",
        "okta.users.appAssignment.manage",
    ],
    "WORKFLOWS_ADMIN": [
        "okta.workflows.flows.invoke",
        "okta.workflows.flows.manage",
        "okta.workflows.flows.folders.manage",
        "okta.workflows.tables.manage",
        "okta.workflows.connections.manage",
        "okta.workflows.connectors.manage",
    ],
}


class BuiltInRolePermission(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    label: str

    # Custom fields for easier querying
    role_id: str
    role_label: str
