from dataclasses import dataclass, field
from datetime import datetime
from typing import ClassVar

from dlt.common.libs.pydantic import DltConfig
from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, ConfigDict, Field

from openhound_okta.graph import OktaNode, OktaNodeProperties
from openhound_okta.kinds import edges as ek, nodes as nk
from openhound_okta.main import app


@dataclass
class GroupProperties(OktaNodeProperties):
    """Properties for the Okta_Group node"""

    type: str
    created: datetime
    last_updated: datetime | None = None
    last_membership_updated: datetime | None = None
    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )


class GroupProfile(BaseModel):
    name: str | None = None
    description: str | None = None

    # AD specific fields
    windows_domain_qualified_name: str | None = Field(
        default=None, alias="windowsDomainQualifiedName"
    )
    dn: str | None = None
    external_id: str | None = Field(default=None, alias="externalId")
    sam_account_name: str | None = Field(default=None, alias="samAccountName")
    object_sid: str | None = Field(default=None, alias="objectSid")


class Stat(BaseModel):
    users_count: int = Field(alias="usersCount")
    apps_count: int = Field(alias="appsCount")
    has_admin_privilege: bool = Field(alias="hasAdminPrivilege")


class Embedded(BaseModel):
    stats: Stat


class Source(BaseModel):
    id: str


@app.asset(
    description="Okta group asset",
    node=NodeDef(
        icon="users",
        kind=nk.GROUP,
        description="Okta group node",
        properties=GroupProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.ORG,
            end=nk.GROUP,
            kind=ek.CONTAINS,
            description="Organization contains group",
            traversable=False,
        ),
        EdgeDef(
            start=nk.APPLICATION,
            end=nk.GROUP,
            kind=ek.GROUP_PULL,
            description="Application pulls group from external source",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.GROUP,
            kind=ek.MEMBERSHIP_SYNC,
            description="Org2org membership sync",
            traversable=True,
        ),
        EdgeDef(
            start=nk.AD_GROUP,
            end=nk.GROUP,
            kind=ek.MEMBERSHIP_SYNC,
            description="AD membership sync",
            traversable=True,
        ),
    ],
)
class Group(BaseAsset):
    model_config = ConfigDict(populate_by_name=True)
    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    id: str
    created: datetime
    type: str
    last_membership_updated: datetime | None = Field(
        default=None, alias="lastMembershipUpdated"
    )
    object_class: list[str] = Field(alias="objectClass", default_factory=list)
    last_updated: datetime | None = Field(default=None, alias="lastUpdated")
    profile: GroupProfile | None = None
    embedded: Embedded = Field(alias="_embedded")
    source: Source | None = None

    @property
    def as_node(self):
        profile_name = self.profile.name if self.profile else None
        return OktaNode(
            kinds=[nk.GROUP],
            properties=GroupProperties(
                tenant=self._lookup.org_id(),
                id=self.id,
                name=profile_name or self.id,
                displayname=profile_name or self.id,
                type=self.type,
                created=self.created,
                last_updated=self.last_updated,
                last_membership_updated=self.last_membership_updated,
                environmentid=self._lookup.org_id(),
            ),
        )

    @property
    def _membership_sync_inbound_ad_edge(self):
        if (
                "okta:windows_security_principal" in self.object_class
                and self.profile.object_sid
        ):
            yield Edge(
                kind=ek.MEMBERSHIP_SYNC,
                start=EdgePath(value=self.profile.object_sid, match_by="id"),
                end=EdgePath(value=self.id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _group_pull_edge(self):
        if self.source and self.source.id and self._lookup.application_exists(self.source.id):
            yield Edge(
                kind=ek.GROUP_PULL,
                start=EdgePath(value=self.source.id, match_by="id"),
                end=EdgePath(value=self.id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _contains_edges(self):
        yield Edge(
            kind=ek.CONTAINS,
            start=EdgePath(value=self._lookup.org_id(), match_by="id"),
            end=EdgePath(value=self.id, match_by="id"),
            properties=EdgeProperties(traversable=False),
        )

    @property
    def _membership_sync_inbound_app_edge(self):
        # TODO: Validate logic if this is just based on source id, there is no existing edge in the test tenant
        if self.type == "APP_GROUP" and "okta:user_group" in self.object_class:
            yield Edge(
                kind=ek.MEMBERSHIP_SYNC,
                start=EdgePath(value=self.source.id, match_by="id"),
                end=EdgePath(value=self.id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        # Double check: _membership_sync_inbound_app_edge
        yield from self._contains_edges
        yield from self._membership_sync_inbound_ad_edge
        yield from self._group_pull_edge
