from .declarative import RouteProfile, RouteTemplate, RouteVariable
from .validators import (
    github_slug,
    host_label,
    host_scope,
    https_origin,
    present_string,
    slack_domain,
)


OIN_ROUTE_PROFILES = (
    RouteProfile(
        profile_id="asana",
        app_keys=("asana",),
        variables=(),
        routes=(
            RouteTemplate(
                acs="https://app.asana.com/-/saml/consume",
                sp_entity="https://app.asana.com",
                acs_variables=(),
                sp_entity_variables=(),
                acs_static_source="documented_static_asana_acs",
                sp_entity_static_source="observed_static_asana_audience",
            ),
        ),
        target_product_family="asana",
        route_source="documented_asana_default_route",
        extraction_mode="allowlisted_static_default_route",
        evidence_references=(
            "https://help.asana.com/s/article/authentication-and-access-management-options-for-paid-plans?language=en_US",
            "https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Asana.html",
            "docs/saml-oin-route-evidence.md#asana-default-promotion",
        ),
        evidence_reviewed_at="2026-08-15",
    ),
    RouteProfile(
        profile_id="okta_org2org",
        app_keys=("okta_org2org",),
        variables=(
            RouteVariable(
                name="acs_url",
                app_field="acsUrl",
                validator=present_string,
                diagnostic="missing_settings.app.acsUrl",
            ),
            RouteVariable(
                name="sp_entity_id",
                app_field="audRestriction",
                validator=present_string,
                diagnostic="missing_settings.app.audRestriction",
            ),
        ),
        routes=(
            RouteTemplate(
                acs="{acs_url}",
                sp_entity="{sp_entity_id}",
                acs_variables=("acs_url",),
                sp_entity_variables=("sp_entity_id",),
            ),
        ),
        target_product_family="okta_org2org",
        route_source="settings.app",
        extraction_mode="oin_explicit_fields",
        evidence_references=("openhound_saml:os-0bef",),
        evidence_reviewed_at="2026-07-13",
    ),
    RouteProfile(
        profile_id="jamf_pro",
        app_keys=("jamfsoftwareserver",),
        variables=(
            RouteVariable(
                name="domain",
                app_field="domain",
                validator=host_scope,
                diagnostic="missing_or_malformed_settings.app.domain",
            ),
        ),
        routes=(
            RouteTemplate(
                acs="https://{domain}/saml/SSO",
                sp_entity="https://{domain}/saml/metadata",
                acs_variables=("domain",),
                sp_entity_variables=("domain",),
            ),
        ),
        target_product_family="jamf_pro",
        route_source="settings.app+documented_jamf_route",
        extraction_mode="allowlisted_deterministic_route",
        evidence_references=("openhound_saml:os-0bef",),
        evidence_reviewed_at="2026-07-13",
    ),
    RouteProfile(
        profile_id="github_enterprise",
        app_keys=("githubenterprisemanageduser",),
        variables=(
            RouteVariable(
                name="enterprise_name",
                app_field="enterpriseName",
                validator=github_slug,
                diagnostic=("missing_or_malformed_settings.app.enterpriseName"),
            ),
        ),
        routes=(
            RouteTemplate(
                acs="https://github.com/enterprises/{enterprise_name}/saml/consume",
                sp_entity="https://github.com/enterprises/{enterprise_name}",
                acs_variables=("enterprise_name",),
                sp_entity_variables=("enterprise_name",),
            ),
        ),
        target_product_family="github_enterprise",
        route_source="settings.app+documented_github_route",
        extraction_mode="allowlisted_deterministic_route",
        evidence_references=("openhound_saml:os-0bef",),
        evidence_reviewed_at="2026-07-13",
    ),
    RouteProfile(
        profile_id="palo_alto_globalprotect",
        app_keys=("panw_globalprotect",),
        variables=(
            RouteVariable(
                name="base_url",
                app_field="baseURL",
                validator=https_origin,
                diagnostic="missing_or_malformed_settings.app.baseURL",
            ),
        ),
        routes=(
            RouteTemplate(
                acs="{base_url}/SAML20/SP/ACS",
                sp_entity="{base_url}/SAML20/SP",
                acs_variables=("base_url",),
                sp_entity_variables=("base_url",),
            ),
        ),
        target_product_family="palo_alto_globalprotect",
        route_source="settings.app+documented_globalprotect_route",
        extraction_mode="allowlisted_deterministic_route",
        evidence_references=(
            "https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Palo-Alto-Networks-GlobalProtect.html",
            "https://docs.paloaltonetworks.com/prisma-access/administration/prisma-access-advanced-deployments/mobile-user-globalprotect-advanced-deployments/configure-multiple-portals-in-prisma-access",
        ),
        evidence_reviewed_at="2026-08-13",
    ),
    RouteProfile(
        profile_id="slack",
        app_keys=("slack",),
        variables=(
            RouteVariable(
                name="domain",
                app_field="domain",
                validator=slack_domain,
                diagnostic="missing_or_malformed_settings.app.domain",
            ),
        ),
        routes=(
            RouteTemplate(
                acs="https://{domain}.slack.com/sso/saml",
                sp_entity="https://slack.com",
                acs_variables=("domain",),
                sp_entity_variables=(),
                sp_entity_static_source="documented_static_slack_sp_entity",
            ),
        ),
        target_product_family="slack",
        route_source="settings.app+documented_slack_route",
        extraction_mode="allowlisted_deterministic_route",
        evidence_references=(
            "https://developer.okta.com/docs/api/openapi/okta-management/management/tags/application/",
            "https://help.okta.com/en-us/content/topics/provisioning/slack/slck-integrate-slack.htm",
            "https://slack.com/help/articles/205168057-Custom-SAML-single-sign-on",
        ),
        evidence_reviewed_at="2026-08-13",
    ),
    RouteProfile(
        profile_id="zoom_single_vanity",
        app_keys=("zoomus",),
        variables=(
            RouteVariable(
                name="subdomain",
                app_field="subDomain",
                validator=host_label,
                diagnostic="missing_or_malformed_settings.app.subDomain",
            ),
        ),
        routes=(
            RouteTemplate(
                acs="https://{subdomain}.zoom.us/saml/SSO",
                sp_entity="https://{subdomain}.zoom.us",
                acs_variables=("subdomain",),
                sp_entity_variables=("subdomain",),
            ),
        ),
        target_product_family="zoom",
        route_source="settings.app+documented_zoom_single_vanity_route",
        extraction_mode="allowlisted_deterministic_route",
        evidence_references=(
            "https://developer.okta.com/docs/api/openapi/okta-management/management/tags/application/",
            "https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063256",
        ),
        evidence_reviewed_at="2026-08-13",
    ),
)
