-- Ephemeral OIN catalog research matrix.
--
-- This is reproducible experiment input for disposable lab applications. It is
-- not persistent simulated-environment desired state and must never be consumed by
-- environment deployment.

CREATE TABLE matrix_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT INTO matrix_metadata (key, value) VALUES ('schema_version', '3');

CREATE TABLE oin_probe_cases (
    case_id TEXT PRIMARY KEY,
    app_key TEXT NOT NULL,
    variant TEXT NOT NULL,
    sign_on_mode TEXT NOT NULL CHECK (sign_on_mode = 'SAML_2_0'),
    settings_app_json TEXT NOT NULL,
    readiness TEXT NOT NULL CHECK (readiness IN ('ready', 'discovery', 'blocked')),
    purpose TEXT NOT NULL,
    evidence TEXT NOT NULL
);

-- Active tracing details stay separate so the broad catalog matrix retains its
-- compact, stable row contract. Values are synthetic public research inputs.
CREATE TABLE oin_probe_active_options (
    case_id TEXT PRIMARY KEY,
    app_link_label_suffix TEXT,
    assignment_profile_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (case_id) REFERENCES oin_probe_cases (case_id)
);

-- Publicly documented field contracts that are ready for a guarded lab probe.
INSERT INTO oin_probe_cases VALUES
('globalprotect-origin', 'panw_globalprotect', 'HTTPS origin', 'SAML_2_0',
 '{"baseURL":"https://vpn.oin-lab.invalid"}', 'ready',
 'Observe materialized GlobalProtect settings from a reserved non-routable origin.',
 'Okta GlobalProtect setup guide and Palo Alto SAML route documentation'),
('slack-workspace', 'slack', 'Workspace', 'SAML_2_0',
 '{"domain":"oin-lab-workspace"}', 'ready',
 'Observe the ordinary Slack workspace route derived from settings.app.domain.',
 'Current Okta Management OpenAPI Slack schema and Slack SAML documentation'),
('slack-enterprise-grid', 'slack', 'Enterprise Grid', 'SAML_2_0',
 '{"domain":"oin-lab.enterprise"}', 'ready',
 'Observe the Slack Enterprise Grid domain convention without a real workspace.',
 'Okta Slack Enterprise Grid guidance and Slack SAML documentation'),
('zoom-single-vanity', 'zoomus', 'Single vanity URL', 'SAML_2_0',
 '{"subDomain":"oin-lab"}', 'ready',
 'Observe the single-vanity Zoom route derived from settings.app.subDomain.',
 'Current Okta Management OpenAPI Zoom schema and Zoom Okta documentation'),
('salesforce-production-standard', 'salesforce', 'Production standard', 'SAML_2_0',
 '{"instanceType":"PRODUCTION","integrationType":"STANDARD"}', 'ready',
 'Compare Salesforce production defaults with other supported schema variants.',
 'Current Okta Management OpenAPI Salesforce schema'),
('salesforce-sandbox-standard', 'salesforce', 'Sandbox standard', 'SAML_2_0',
 '{"instanceType":"SANDBOX","integrationType":"STANDARD"}', 'ready',
 'Compare Salesforce sandbox defaults with production.',
 'Current Okta Management OpenAPI Salesforce schema'),
('salesforce-government-standard', 'salesforce', 'Government standard', 'SAML_2_0',
 '{"instanceType":"GOVERNMENT","integrationType":"STANDARD"}', 'ready',
 'Compare Salesforce government defaults with other environments.',
 'Current Okta Management OpenAPI Salesforce schema'),
('salesforce-production-portal', 'salesforce', 'Production portal', 'SAML_2_0',
 '{"instanceType":"PRODUCTION","integrationType":"PORTAL"}', 'ready',
 'Compare Salesforce portal route materialization with standard integration.',
 'Current Okta Management OpenAPI Salesforce schema'),
('salesforce-production-community', 'salesforce', 'Production community', 'SAML_2_0',
 '{"instanceType":"PRODUCTION","integrationType":"COMMUNITY"}', 'ready',
 'Compare Salesforce community route materialization with standard integration.',
 'Current Okta Management OpenAPI Salesforce schema'),
('workday-site-url', 'workday', 'Tenant site URL', 'SAML_2_0',
 '{"siteURL":"https://workday.oin-lab.invalid"}', 'ready',
 'Observe which route fields are materialized from the documented Workday siteURL.',
 'Current Okta Management OpenAPI application example and Okta Workday guide');

-- Variant probes that need an explicit operator decision or a first-pass schema
-- error before they can be promoted to ready. They run only with
-- --include-discovery and an explicit case selection.
INSERT INTO oin_probe_cases VALUES
('zoom-multi-idp', 'zoomus', 'Multiple vanity URLs or IdPs', 'SAML_2_0',
 '{"acsUrl":"https://zoom.us/saml2/sso/oin-lab","audience":"https://zoom.us/sp/oin-lab"}', 'discovery',
 'Determine the exact collected field names for the downstream-generated Zoom variant.',
 'Zoom Okta documentation; current public Okta schema does not expose these fields'),
('adobecreativecloud-default', 'adobecreativecloud', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('alertmediacom-default', 'alertmediacom', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('amazon-aws-sso-default', 'amazon_aws_sso', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Identify this catalog key and its environment/ACS selection contract.', 'Public Okta AWS guide documents environment-specific ACS behavior'),
('asana-default', 'asana', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('atlassian-default', 'atlassian', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization/site-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('boxnet-default', 'boxnet', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Determine whether Box routes are static or downstream-generated.', 'Okta Box guide currently relies on downstream SSO activation'),
('cisco-common-identity-default', 'ciscocommonidentity', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('cisco-meraki-default', 'ciscomeraki', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('citrix-netscaler-default', 'citrixnetscalergateway_saml', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover gateway-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('cloudconsole-default', 'cloudconsole', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Identify the exact product and route contract for this ambiguous key.', 'Public catalog identity review pending'),
('datadog-default', 'datadog', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover the Company ID field and regional route behavior.', 'Okta Datadog guide documents a downstream-generated Company ID'),
('dialpad-default', 'dialpad', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('docusign-default', 'docusign', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover account/environment route inputs.', 'Public catalog and vendor documentation review pending'),
('postman-default', 'getpostman', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization/team route inputs.', 'Public catalog and vendor documentation review pending'),
('island-default', 'island', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields without aliasing the management-console app.', 'Public catalog and vendor documentation review pending'),
('island-management-console-default', 'island_managementconsole', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover management-console-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('logicmonitor-default', 'logicmonitor', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover account/domain route inputs.', 'Public catalog and vendor documentation review pending'),
('logmein-default', 'logmein', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Identify product/account variants and route inputs.', 'Public catalog and vendor documentation review pending'),
('mimecast-admin-default', 'mimecastadmin', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Mimecast Admin region/product inputs.', 'Public catalog and vendor documentation review pending'),
('mimecast-ppv3-default', 'mimecastppv3', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Personal Portal region/product inputs.', 'Public catalog and vendor documentation review pending'),
('motus-default', 'motus', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('navan-default', 'navan', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('novatus-default', 'novatus', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Identify the current product and required route inputs.', 'Public catalog and vendor documentation review pending'),
('odesk-default', 'odesk', 'Legacy catalog default', 'SAML_2_0', '{}', 'discovery', 'Determine whether this legacy integration remains installable and stable.', 'Current product identity and public route review pending'),
('oracle-cloud-iam-default', 'oraclecloudinfrastructureiam', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover tenancy/region-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('pagerduty-default', 'pagerduty', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover the Organization Subdomain field and materialized route.', 'Okta PagerDuty guide documents the organization subdomain input'),
('palo-alto-saml-default', 'paloaltonetworkssaml', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Determine this family contract independently of GlobalProtect.', 'Public catalog and vendor documentation review pending'),
('readcube-default', 'readcube', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('servicenow-ud-default', 'servicenow_ud', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover instance and multi-provider SSO route inputs.', 'Okta ServiceNow guide documents downstream IdP configuration'),
('sentry-default', 'sentry', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('sharefile-default', 'sharefile', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover account/control-plane route inputs.', 'Public catalog and vendor documentation review pending'),
('showpad-default', 'showpad', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization/subdomain route inputs.', 'Public catalog and vendor documentation review pending'),
('simplelegal-default', 'simplelegal', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover required instance fields and materialized sign-on settings.', 'Public catalog and vendor documentation review pending'),
('tableau-online-default', 'tableauonline', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover site/pod-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('vanta-default', 'vanta', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover organization-specific route inputs.', 'Public catalog and vendor documentation review pending'),
('workiva-default', 'workiva', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Confirm that ACS and audience remain downstream-generated explicit inputs.', 'Okta Workiva guide instructs copying both values from Workiva'),
('xmatters-default', 'xmatters', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover instance/region-specific route inputs.', 'Public catalog and vendor documentation review pending');

-- Additional SAML-capable catalog targets selected from Okta's public
-- Businesses at Work popularity reports. Empty settings are deliberate:
-- each case must first be run individually to learn its current required
-- installation fields, then replaced by a reviewed variant matrix.
INSERT INTO oin_probe_cases VALUES
('adp-default', 'adp', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover the current generic ADP SAML integration contract.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('amazon-aws-default', 'amazon_aws', 'Account federation with synthetic role', 'SAML_2_0',
 '{"appFilter":"okta","awsEnvironmentType":"aws.amazon","identityProviderArn":"arn:aws:iam::000000000000:saml-provider/oin-lab","joinAllRoles":false,"roleValuePattern":"arn:aws:iam::${accountid}:saml-provider/oin-lab,arn:aws:iam::${accountid}:role/${role}","sessionDuration":3600,"useGroupMapping":false}',
 'discovery', 'Discover the standard AWS SAML route with a non-live account and role assignment.',
 '2024-2026 Businesses at Work popular-app cohorts; Okta AWS Account Federation guide; 2026-08-14 catalog inventory'),
('amazon-business-default', 'amazon_business', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Amazon Business account-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('bamboohr-default', 'bamboohr', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover BambooHR company-domain route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('bitwarden-default', 'bitwarden', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Bitwarden organization-specific route inputs.', '2025 and 2026 Businesses at Work growth cohorts; 2026-08-14 catalog inventory'),
('concur-solutions-default', 'concur-solutions', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover SAP Concur account and environment inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('crowdstrike-default', 'crowdstrike', 'Falcon', 'SAML_2_0', '{}', 'discovery', 'Discover CrowdStrike Falcon cloud and account inputs.', '2026 Businesses at Work growth cohort; 2026-08-14 catalog inventory'),
('dropbox-business-default', 'dropbox_for_business', 'Business', 'SAML_2_0', '{}', 'discovery', 'Discover Dropbox Business team-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('envoy-scim11-default', 'envoy', 'SCIM 1.1 catalog variant', 'SAML_2_0', '{}', 'discovery', 'Discover SAML fields retained by the Envoy SCIM 1.1 integration.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('envoy-scim20-default', 'envoycom', 'SCIM 2.0 catalog variant', 'SAML_2_0', '{}', 'discovery', 'Discover SAML fields retained by the Envoy SCIM 2.0 integration.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('envoy-global-default', 'envoyglobal', 'Global catalog variant', 'SAML_2_0', '{}', 'discovery', 'Discover Envoy Global route inputs independently from Envoy visitor-management variants.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('zip-default', 'evergreen', 'Current Zip catalog integration', 'SAML_2_0', '{}', 'discovery', 'Discover Zip organization-specific route inputs.', '2025 Businesses at Work growth cohort; 2026-08-14 catalog inventory'),
('expensify-default', 'expensifysaml', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Expensify account-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('figma-default', 'figma', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Figma organization-specific route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('freshworks-default', 'freshworks', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Freshworks product and account route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('github-cloud-org-default', 'githubcloud', 'Enterprise Cloud organization', 'SAML_2_0', '{}', 'discovery', 'Discover GitHub organization-specific SAML route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('github-cloud-enterprise-default', 'ghecenterprisesaml', 'Enterprise Cloud enterprise account', 'SAML_2_0', '{}', 'discovery', 'Discover GitHub enterprise-account SAML route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('google-workspace-default', 'google', 'Workspace', 'SAML_2_0', '{}', 'discovery', 'Discover Google Workspace domain-specific route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('greenhouse-recruiting-default', 'greenhouseio', 'Recruiting', 'SAML_2_0', '{}', 'discovery', 'Discover Greenhouse Recruiting route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('greenhouse-onboarding-default', 'parklet', 'Onboarding', 'SAML_2_0', '{}', 'discovery', 'Discover Greenhouse Onboarding route inputs separately from Recruiting.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('hubspot-default', 'hubspotsaml', 'SAML catalog integration', 'SAML_2_0', '{}', 'discovery', 'Discover HubSpot account-specific SAML route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('jamf-pro-admin-default', 'jamfsoftwareserver', 'Admin Console', 'SAML_2_0', '{}', 'discovery', 'Discover Jamf Pro server-specific route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('jenkins-default', 'jenkins', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Jenkins server-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('knowbe4-default', 'knowbe4', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover KnowBe4 account and region route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('lucid-default', 'lucid', 'Current Lucid integration', 'SAML_2_0', '{}', 'discovery', 'Discover Lucid organization-specific route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('mimecast-portal-v2-default', 'mimecast', 'Personal Portal v2', 'SAML_2_0', '{}', 'discovery', 'Discover the legacy Mimecast Personal Portal route contract.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('miro-default', 'realtime_board', 'Miro', 'SAML_2_0', '{}', 'discovery', 'Discover Miro organization-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('monday-default', 'mondaycom', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover monday.com account-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('netsuite-default', 'netsuite', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover NetSuite account and environment route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('notion-default', 'notion', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Notion workspace-specific route inputs.', '2026 Businesses at Work country growth cohort; 2026-08-14 catalog inventory'),
('oracle-cloud-default', 'oraclecloudinfrastructure', 'Cloud Infrastructure', 'SAML_2_0', '{}', 'discovery', 'Discover Oracle Cloud tenancy and region route inputs.', '2025 Businesses at Work growth cohort; 2026-08-14 catalog inventory'),
('palo-alto-prisma-access-default', 'palo_alto_networks_prisma_access', 'Prisma Access', 'SAML_2_0', '{}', 'discovery', 'Discover Prisma Access route inputs independently from GlobalProtect and the Admin UI.', '2025-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('ramp-default', 'rampcom', 'SAML catalog integration', 'SAML_2_0', '{}', 'discovery', 'Discover the SAML-capable Ramp integration contract.', '2026 Businesses at Work growth cohort; 2026-08-14 catalog inventory'),
('ringcentral-default', 'ringcentral_saml', 'SAML catalog integration', 'SAML_2_0', '{}', 'discovery', 'Discover RingCentral account and regional route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('sigma-on-aws-default', 'sigmaonaws', 'Sigma on AWS catalog variant', 'SAML_2_0', '{}', 'discovery', 'Determine whether the report brand corresponds to this SAML-capable Sigma variant.', '2026 Businesses at Work growth cohort; 2026-08-14 catalog inventory'),
('smartsheet-default', 'smartsheet', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover the original Smartsheet route contract.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('smartsheet-v2-default', 'smartsheet_v2', 'Version 2', 'SAML_2_0', '{}', 'discovery', 'Discover the current Smartsheet v2 route contract separately.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('snowflake-default', 'snowflake', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Snowflake account, region, and cloud route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('splunk-enterprise-default', 'splunk', 'Enterprise', 'SAML_2_0', '{}', 'discovery', 'Discover Splunk Enterprise server-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('splunk-cloud-default', 'splunkcloud', 'Cloud', 'SAML_2_0', '{}', 'discovery', 'Discover Splunk Cloud stack and region route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('tableau-server-default', 'tableau', 'Server', 'SAML_2_0', '{}', 'discovery', 'Discover Tableau Server deployment-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('uber-business-default', 'uberbusiness', 'Business SAML catalog variant', 'SAML_2_0', '{}', 'discovery', 'Determine whether the report brand corresponds to the SAML-capable Uber for Business integration.', '2025-2026 Businesses at Work growth cohorts; 2026-08-14 catalog inventory'),
('umbrella-admin-default', 'opendns', 'Admin SSO', 'SAML_2_0', '{}', 'discovery', 'Discover Cisco Umbrella organization-specific admin route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('webex-meetings-default', 'webex', 'Meetings', 'SAML_2_0', '{}', 'discovery', 'Discover Webex Meetings site-specific route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('zendesk-default', 'zendesk', 'Catalog default', 'SAML_2_0', '{}', 'discovery', 'Discover Zendesk account and custom SSO route inputs.', '2024-2026 Businesses at Work popular-app cohorts; 2026-08-14 catalog inventory'),
('zscaler-internet-access-default', 'zscalerbyz', 'Internet Access', 'SAML_2_0', '{}', 'discovery', 'Discover Zscaler Internet Access cloud and account route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory'),
('zscaler-private-access-default', 'zscaler_private_access', 'Private Access', 'SAML_2_0', '{}', 'discovery', 'Discover Zscaler Private Access cloud and account route inputs.', '2024 Businesses at Work popular-app cohort; 2026-08-14 catalog inventory');

-- Known non-generic cases. These remain represented for research accounting but
-- cannot be executed by the harness.
INSERT INTO oin_probe_cases VALUES
('okta-org2org-explicit', 'okta_org2org', 'Explicit downstream trust', 'SAML_2_0', '{}', 'blocked',
 'Org2Org requires authoritative target-org ACS and audience values and may be unavailable in free lab orgs.',
 'Current Okta Management OpenAPI and Org2Org guide'),
('scim2-test-app', 'scim2testapp', 'Test/private service', 'SAML_2_0', '{}', 'blocked',
 'Do not synthesize a public route for an instance-defined test service.',
 'OIN lab fail-closed scope');

-- Recovery variants discovered by the first active sweep. Atlassian exposes
-- eight product links under one catalog app; each trace pins one dynamic label
-- suffix rather than relying on Okta's link ordering.
INSERT INTO oin_probe_cases VALUES
('atlassian-jira', 'atlassian', 'Jira SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Jira launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-confluence', 'atlassian', 'Confluence SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Confluence launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-statuspage', 'atlassian', 'Statuspage SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Statuspage launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-trello', 'atlassian', 'Trello SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Trello launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-bitbucket', 'atlassian', 'Bitbucket SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Bitbucket launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-compass', 'atlassian', 'Compass SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Compass launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-jsm', 'atlassian', 'Jira Service Management SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Jira Service Management launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory'),
('atlassian-loom', 'atlassian', 'Loom SAML link', 'SAML_2_0', '{}', 'discovery', 'Trace the Loom launch-link variant.', '2026-08-17 Preview1 active sweep app-link inventory');

INSERT INTO oin_probe_active_options VALUES
('amazon-aws-default', NULL, '{"samlRoles":["000000000000 -- oin-lab-role"]}'),
('atlassian-jira', ' Jira SAML', '{}'),
('atlassian-confluence', ' Confluence SAML', '{}'),
('atlassian-statuspage', ' Statuspage SAML', '{}'),
('atlassian-trello', ' Trello SAML', '{}'),
('atlassian-bitbucket', ' Bitbucket SAML', '{}'),
('atlassian-compass', ' Compass SAML', '{}'),
('atlassian-jsm', ' Jira Service Management SAML', '{}'),
('atlassian-loom', ' Loom SAML', '{}');

-- Public popularity evidence is kept separate from executable probes. Reported
-- product names are brands, not stable Okta catalog keys, and must be resolved
-- against a dated catalog inventory before an app is selected for testing.
CREATE TABLE popular_app_reports (
    report_year INTEGER NOT NULL,
    cohort TEXT NOT NULL,
    source_url TEXT NOT NULL,
    source_notes TEXT NOT NULL,
    PRIMARY KEY (report_year, cohort)
);

CREATE TABLE popular_app_report_entries (
    report_year INTEGER NOT NULL,
    cohort TEXT NOT NULL,
    report_name TEXT NOT NULL,
    rank INTEGER,
    growth_percent INTEGER,
    PRIMARY KEY (report_year, cohort, report_name),
    FOREIGN KEY (report_year, cohort)
        REFERENCES popular_app_reports (report_year, cohort)
);

INSERT INTO popular_app_reports VALUES
(2024, 'most-popular-50',
 'https://www.okta.com/sites/default/files/2024-04/Okta-2024_Businesses_at_Work.pdf',
 'Official report chart of the 50 most popular apps of 2023; the chart is not a rank ordering.'),
(2025, 'overall-top-15',
 'https://www.okta.com/sites/default/files/2025-03/Businesses-at-Work-Infographic.pdf',
 'Official infographic ranking the most popular apps in 2024 by number of customers.'),
(2025, 'growth-callouts',
 'https://www.okta.com/reports/businesses-at-work-archive/businesses-at-work-2025/',
 'Public report page names growth leaders and new additions but does not publish their complete rank order.'),
(2026, 'overall-top-15',
 'https://prtimes.jp/main/html/rd/p/000000176.000063011.html',
 'Public mirror of the Okta Japan press release includes the complete Okta top-15 chart.'),
(2026, 'fastest-growing-10',
 'https://prtimes.jp/main/html/rd/p/000000176.000063011.html',
 'Public mirror of the Okta Japan press release includes the complete Okta growth chart and percentages.');

INSERT INTO popular_app_report_entries VALUES
(2024, 'most-popular-50', 'Cisco Meraki', NULL, NULL),
(2024, 'most-popular-50', 'Google Workspace', NULL, NULL),
(2024, 'most-popular-50', 'Salesforce', NULL, NULL),
(2024, 'most-popular-50', 'Cisco AnyConnect', NULL, NULL),
(2024, 'most-popular-50', 'Zscaler', NULL, NULL),
(2024, 'most-popular-50', 'BambooHR', NULL, NULL),
(2024, 'most-popular-50', 'Zoom', NULL, NULL),
(2024, 'most-popular-50', 'DocuSign', NULL, NULL),
(2024, 'most-popular-50', 'Expensify', NULL, NULL),
(2024, 'most-popular-50', 'Mimecast', NULL, NULL),
(2024, 'most-popular-50', 'ServiceNow', NULL, NULL),
(2024, 'most-popular-50', 'Smartsheet', NULL, NULL),
(2024, 'most-popular-50', 'GitHub', NULL, NULL),
(2024, 'most-popular-50', 'Box', NULL, NULL),
(2024, 'most-popular-50', 'Zendesk', NULL, NULL),
(2024, 'most-popular-50', 'Tableau', NULL, NULL),
(2024, 'most-popular-50', 'Palo Alto Networks GlobalProtect', NULL, NULL),
(2024, 'most-popular-50', 'KnowBe4', NULL, NULL),
(2024, 'most-popular-50', 'Dropbox', NULL, NULL),
(2024, 'most-popular-50', '1Password', NULL, NULL),
(2024, 'most-popular-50', 'Greenhouse', NULL, NULL),
(2024, 'most-popular-50', 'Datadog', NULL, NULL),
(2024, 'most-popular-50', 'Miro', NULL, NULL),
(2024, 'most-popular-50', 'HubSpot', NULL, NULL),
(2024, 'most-popular-50', 'SAP Concur', NULL, NULL),
(2024, 'most-popular-50', 'Snowflake', NULL, NULL),
(2024, 'most-popular-50', 'Oracle NetSuite', NULL, NULL),
(2024, 'most-popular-50', 'Figma', NULL, NULL),
(2024, 'most-popular-50', 'Adobe Creative Cloud', NULL, NULL),
(2024, 'most-popular-50', 'PagerDuty', NULL, NULL),
(2024, 'most-popular-50', 'Amazon Business', NULL, NULL),
(2024, 'most-popular-50', 'AWS', NULL, NULL),
(2024, 'most-popular-50', 'Jamf Pro', NULL, NULL),
(2024, 'most-popular-50', 'Freshworks', NULL, NULL),
(2024, 'most-popular-50', 'Envoy', NULL, NULL),
(2024, 'most-popular-50', 'LastPass', NULL, NULL),
(2024, 'most-popular-50', 'ADP', NULL, NULL),
(2024, 'most-popular-50', 'Asana', NULL, NULL),
(2024, 'most-popular-50', 'Workday', NULL, NULL),
(2024, 'most-popular-50', 'Sentry', NULL, NULL),
(2024, 'most-popular-50', 'Splunk', NULL, NULL),
(2024, 'most-popular-50', 'RingCentral', NULL, NULL),
(2024, 'most-popular-50', 'Webex', NULL, NULL),
(2024, 'most-popular-50', 'monday.com', NULL, NULL),
(2024, 'most-popular-50', 'Cisco Umbrella', NULL, NULL),
(2024, 'most-popular-50', 'Jenkins', NULL, NULL),
(2024, 'most-popular-50', 'Microsoft 365', NULL, NULL),
(2024, 'most-popular-50', 'Slack', NULL, NULL),
(2024, 'most-popular-50', 'Atlassian', NULL, NULL),
(2024, 'most-popular-50', 'Lucidchart', NULL, NULL),
(2025, 'overall-top-15', 'Microsoft 365', 1, NULL),
(2025, 'overall-top-15', 'Google Workspace', 2, NULL),
(2025, 'overall-top-15', 'AWS', 3, NULL),
(2025, 'overall-top-15', 'Salesforce', 4, NULL),
(2025, 'overall-top-15', 'Zoom', 5, NULL),
(2025, 'overall-top-15', 'Atlassian Product Suite', 6, NULL),
(2025, 'overall-top-15', 'Slack', 7, NULL),
(2025, 'overall-top-15', 'DocuSign', 8, NULL),
(2025, 'overall-top-15', 'GitHub', 9, NULL),
(2025, 'overall-top-15', 'KnowBe4', 10, NULL),
(2025, 'overall-top-15', 'Cisco Meraki', 11, NULL),
(2025, 'overall-top-15', 'Lucid', 12, NULL),
(2025, 'overall-top-15', 'Jamf Pro', 13, NULL),
(2025, 'overall-top-15', 'Palo Alto Networks', 14, NULL),
(2025, 'overall-top-15', 'Zendesk', 15, NULL),
(2025, 'growth-callouts', 'Bitwarden', NULL, NULL),
(2025, 'growth-callouts', 'Tailscale', NULL, NULL),
(2025, 'growth-callouts', 'Drata', NULL, NULL),
(2025, 'growth-callouts', 'Vanta', NULL, NULL),
(2025, 'growth-callouts', 'Zip', NULL, NULL),
(2025, 'growth-callouts', 'Uber', NULL, NULL),
(2025, 'growth-callouts', 'Oracle Cloud Infrastructure', NULL, NULL),
(2026, 'overall-top-15', 'Microsoft 365', 1, NULL),
(2026, 'overall-top-15', 'Google Workspace', 2, NULL),
(2026, 'overall-top-15', 'AWS', 3, NULL),
(2026, 'overall-top-15', 'Salesforce', 4, NULL),
(2026, 'overall-top-15', 'Zoom', 5, NULL),
(2026, 'overall-top-15', 'Slack', 6, NULL),
(2026, 'overall-top-15', 'Atlassian Product Suite', 7, NULL),
(2026, 'overall-top-15', 'GitHub', 8, NULL),
(2026, 'overall-top-15', 'DocuSign', 9, NULL),
(2026, 'overall-top-15', 'KnowBe4', 10, NULL),
(2026, 'overall-top-15', 'Figma', 11, NULL),
(2026, 'overall-top-15', 'Cisco Meraki', 12, NULL),
(2026, 'overall-top-15', 'Lucid', 13, NULL),
(2026, 'overall-top-15', 'Jamf', 14, NULL),
(2026, 'overall-top-15', 'Palo Alto Networks', 15, NULL),
(2026, 'fastest-growing-10', 'NinjaOne', 1, 240),
(2026, 'fastest-growing-10', 'CrowdStrike Falcon', 2, 66),
(2026, 'fastest-growing-10', 'Uber', 3, 63),
(2026, 'fastest-growing-10', 'Ramp', 4, 58),
(2026, 'fastest-growing-10', 'Island', 5, 53),
(2026, 'fastest-growing-10', 'Vanta', 6, 43),
(2026, 'fastest-growing-10', 'NordLayer', 7, 39),
(2026, 'fastest-growing-10', 'Sigma', 8, 39),
(2026, 'fastest-growing-10', 'Tailscale', 9, 36),
(2026, 'fastest-growing-10', 'Bitwarden', 10, 36);

CREATE TABLE popular_app_catalog_targets (
    target_id TEXT PRIMARY KEY,
    report_name TEXT NOT NULL,
    app_key TEXT,
    catalog_display_name TEXT,
    observed_sign_on_modes_json TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (
        disposition IN ('saml_candidate', 'non_saml', 'absent')
    ),
    match_basis TEXT NOT NULL CHECK (
        match_basis IN ('exact_display', 'rebrand', 'brand_variant', 'no_current_match')
    ),
    notes TEXT NOT NULL
);

-- These mappings are a dated 2026-08-14 observation from the authorized
-- Catalog API inventory. Multiple rows intentionally preserve product-family
-- ambiguity instead of pretending a report brand is one stable integration.
INSERT INTO popular_app_catalog_targets VALUES
('1password-current', '1Password', '1password_business', '1Password Enterprise Password Manager', '["BOOKMARK","BROWSER_PLUGIN","OPENID_CONNECT"]', 'non_saml', 'brand_variant', 'No SAML 2.0 mode was advertised by the current catalog entry.'),
('adp-current', 'ADP', 'adp', 'ADP', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Generic ADP integration; product-specific ADP variants remain separate.'),
('adobe-creative-cloud-current', 'Adobe Creative Cloud', 'adobecreativecloud', 'Adobe Creative Cloud', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('amazon-business-current', 'Amazon Business', 'amazon_business', 'Amazon Business', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('asana-current', 'Asana', 'asana', 'Asana', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('atlassian-current', 'Atlassian', 'atlassian', 'Atlassian Cloud', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current cloud product-suite candidate.'),
('atlassian-suite-current', 'Atlassian Product Suite', 'atlassian', 'Atlassian Cloud', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'rebrand', 'Current cloud product-suite candidate.'),
('aws-account-federation', 'AWS', 'amazon_aws', 'AWS Account Federation', '["AWS_FEDERATED_LOGIN","AWS_IAM_ROLE","BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Primary account-federation candidate.'),
('aws-identity-center', 'AWS', 'amazon_aws_sso', 'AWS IAM Identity Center', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Distinct IAM Identity Center candidate.'),
('bamboohr-current', 'BambooHR', 'bamboohr', 'BambooHR', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('bitwarden-current', 'Bitwarden', 'bitwarden', 'Bitwarden', '["OPENID_CONNECT","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('box-current', 'Box', 'boxnet', 'Box', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('cisco-anyconnect-absent', 'Cisco AnyConnect', NULL, NULL, '[]', 'absent', 'no_current_match', 'No catalog display-name match was present in the complete 2026-08-14 inventory.'),
('cisco-meraki-current', 'Cisco Meraki', 'ciscomeraki', 'Cisco Meraki Dashboard SAML', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'SAML-specific current Meraki candidate.'),
('cisco-umbrella-current', 'Cisco Umbrella', 'opendns', 'Cisco Umbrella Admin SSO', '["AUTO_LOGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current admin SSO candidate.'),
('crowdstrike-current', 'CrowdStrike Falcon', 'crowdstrike', 'CrowdStrike Falcon', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('datadog-current', 'Datadog', 'datadog', 'Datadog', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('docusign-current', 'DocuSign', 'docusign', 'DocuSign', '["BROWSER_PLUGIN","SAML_1_1","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('drata-current', 'Drata', 'drata', 'Drata', '["OPENID_CONNECT"]', 'non_saml', 'exact_display', 'Current exact match advertises OIDC only.'),
('dropbox-current', 'Dropbox', 'dropbox_for_business', 'Dropbox Business', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current business SAML candidate.'),
('envoy-scim11', 'Envoy', 'envoy', 'Envoy (SCIM 1.1)', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Legacy provisioning variant with SAML.'),
('envoy-scim20', 'Envoy', 'envoycom', 'Envoy (SCIM 2.0)', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current provisioning variant with SAML.'),
('envoy-global', 'Envoy', 'envoyglobal', 'Envoy Global', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Distinct product sharing the Envoy brand.'),
('expensify-current', 'Expensify', 'expensifysaml', 'Expensify', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('figma-current', 'Figma', 'figma', 'Figma', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('freshworks-current', 'Freshworks', 'freshworks', 'Freshworks', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('github-cloud-org', 'GitHub', 'githubcloud', 'Github Enterprise Cloud - Organization', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Organization-scoped Enterprise Cloud candidate.'),
('github-cloud-enterprise', 'GitHub', 'ghecenterprisesaml', 'Github Enterprise Cloud - Enterprise Accounts', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Enterprise-account-scoped Enterprise Cloud candidate.'),
('google-workspace-current', 'Google Workspace', 'google', 'Google Workspace', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('greenhouse-recruiting', 'Greenhouse', 'greenhouseio', 'Greenhouse Recruiting', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Recruiting product candidate.'),
('greenhouse-onboarding', 'Greenhouse', 'parklet', 'Greenhouse Onboarding', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Onboarding product candidate.'),
('hubspot-current', 'HubSpot', 'hubspotsaml', 'HubSpot', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact SAML catalog display match.'),
('island-current', 'Island', 'island', 'Island', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('jamf-current', 'Jamf', 'jamfsoftwareserver', 'Jamf Pro - Admin Console', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current SAML-capable Jamf Pro admin candidate.'),
('jamf-pro-current', 'Jamf Pro', 'jamfsoftwareserver', 'Jamf Pro - Admin Console', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current SAML-capable Jamf Pro admin candidate.'),
('jenkins-current', 'Jenkins', 'jenkins', 'Jenkins', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('knowbe4-current', 'KnowBe4', 'knowbe4', 'KnowBe4', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('lastpass-current', 'LastPass', 'lastpasssycn', 'LastPass', '["BROWSER_PLUGIN"]', 'non_saml', 'exact_display', 'Current exact match does not advertise SAML.'),
('lucid-current', 'Lucid', 'lucid', 'Lucid', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('lucidchart-current', 'Lucidchart', 'lucid', 'Lucid', '["SAML_2_0"]', 'saml_candidate', 'rebrand', 'Current catalog uses the broader Lucid product name.'),
('microsoft365-current', 'Microsoft 365', 'office365', 'Microsoft Office 365', '["BROWSER_PLUGIN","SAML_1_1"]', 'non_saml', 'rebrand', 'Current primary catalog entry advertises SAML 1.1, not SAML 2.0.'),
('mimecast-portal-v2', 'Mimecast', 'mimecast', 'Mimecast Personal Portal v2', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Personal Portal v2 candidate.'),
('mimecast-admin', 'Mimecast', 'mimecastadmin', 'Mimecast - Admin', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Admin product candidate.'),
('mimecast-portal-v3', 'Mimecast', 'mimecastppv3', 'Mimecast Personal Portal v3', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Personal Portal v3 candidate.'),
('miro-current', 'Miro', 'realtime_board', 'Miro (formerly RealtimeBoard)', '["AUTO_LOGIN","SAML_2_0"]', 'saml_candidate', 'rebrand', 'Current catalog key retains the former product name.'),
('monday-current', 'monday.com', 'mondaycom', 'monday.com', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('netsuite-current', 'Oracle NetSuite', 'netsuite', 'NetSuite', '["AUTO_LOGIN","NETSUITE_SSO","SAML_2_0"]', 'saml_candidate', 'rebrand', 'Current catalog omits the Oracle prefix.'),
('ninjaone-absent', 'NinjaOne', NULL, NULL, '[]', 'absent', 'no_current_match', 'No catalog display-name match was present in the complete 2026-08-14 inventory.'),
('nordlayer-absent', 'NordLayer', NULL, NULL, '[]', 'absent', 'no_current_match', 'No catalog display-name match was present in the complete 2026-08-14 inventory.'),
('oracle-cloud-current', 'Oracle Cloud Infrastructure', 'oraclecloudinfrastructure', 'Oracle Cloud Infrastructure', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Primary current OCI candidate.'),
('oracle-cloud-iam', 'Oracle Cloud Infrastructure', 'oraclecloudinfrastructureiam', 'Oracle Cloud Infrastructure IAM', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Distinct IAM candidate.'),
('pagerduty-current', 'PagerDuty', 'pagerduty', 'PagerDuty', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('palo-alto-admin', 'Palo Alto Networks', 'paloaltonetworkssaml', 'Palo Alto Networks - Admin UI', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Admin UI candidate.'),
('palo-alto-globalprotect-brand', 'Palo Alto Networks', 'panw_globalprotect', 'Palo Alto Networks - GlobalProtect', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'GlobalProtect candidate.'),
('palo-alto-prisma', 'Palo Alto Networks', 'palo_alto_networks_prisma_access', 'Palo Alto Networks - Prisma Access', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Prisma Access candidate.'),
('globalprotect-current', 'Palo Alto Networks GlobalProtect', 'panw_globalprotect', 'Palo Alto Networks - GlobalProtect', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Hyphen difference only; exact product candidate.'),
('ramp-browser', 'Ramp', 'ramp', 'Ramp', '["BROWSER_PLUGIN"]', 'non_saml', 'exact_display', 'One exact-display catalog entry is browser-plugin only.'),
('ramp-saml', 'Ramp', 'rampcom', 'Ramp', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'A second exact-display catalog entry is SAML-capable.'),
('ringcentral-current', 'RingCentral', 'ringcentral_saml', 'RingCentral', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact SAML catalog display match.'),
('salesforce-current', 'Salesforce', 'salesforce', 'Salesforce.com', '["BOOKMARK","BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'rebrand', 'Primary current catalog integration.'),
('sap-concur-current', 'SAP Concur', 'concur-solutions', 'SAP Concur Solutions', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current general Concur SAML candidate.'),
('sentry-current', 'Sentry', 'sentry', 'Sentry', '["AUTO_LOGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('servicenow-current', 'ServiceNow', 'servicenow_ud', 'ServiceNow UD', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Current Universal Directory candidate.'),
('sigma-on-aws', 'Sigma', 'sigmaonaws', 'Sigma on AWS', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Only current catalog display match containing the report brand; association remains provisional.'),
('slack-current', 'Slack', 'slack', 'Slack', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('smartsheet-current', 'Smartsheet', 'smartsheet', 'Smartsheet', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Original integration candidate.'),
('smartsheet-v2', 'Smartsheet', 'smartsheet_v2', 'Smartsheet v2', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Version 2 candidate.'),
('snowflake-current', 'Snowflake', 'snowflake', 'Snowflake', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('splunk-enterprise', 'Splunk', 'splunk', 'Splunk Enterprise', '["AUTO_LOGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Enterprise candidate.'),
('splunk-cloud', 'Splunk', 'splunkcloud', 'Splunk Cloud', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Cloud candidate.'),
('tableau-server', 'Tableau', 'tableau', 'Tableau Server', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Server candidate.'),
('tableau-cloud', 'Tableau', 'tableauonline', 'Tableau Cloud', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Cloud candidate.'),
('tailscale-current', 'Tailscale', 'tailscale', 'Tailscale', '["OPENID_CONNECT"]', 'non_saml', 'exact_display', 'Current exact match advertises OIDC only.'),
('uber-current', 'Uber', 'uber', 'Uber', '["BROWSER_PLUGIN"]', 'non_saml', 'exact_display', 'Exact report-name match is browser-plugin only.'),
('uber-business', 'Uber', 'uberbusiness', 'Uber for Business', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'SAML-capable brand variant; the report does not prove it is the measured integration.'),
('vanta-current', 'Vanta', 'vanta', 'Vanta', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('webex-identity', 'Webex', 'ciscocommonidentity', 'Cisco Webex', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Common Identity candidate.'),
('webex-meetings', 'Webex', 'webex', 'Cisco Webex Meetings', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Meetings candidate.'),
('workday-current', 'Workday', 'workday', 'Workday', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('zendesk-current', 'Zendesk', 'zendesk', 'Zendesk', '["BROWSER_PLUGIN","SAML_2_0","zendeskCustomSSO"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('zip-current', 'Zip', 'evergreen', 'Zip', '["SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match; stable key retains a former product name.'),
('zoom-current', 'Zoom', 'zoomus', 'Zoom', '["OPENID_CONNECT","SAML_2_0"]', 'saml_candidate', 'exact_display', 'Exact current catalog display match.'),
('zscaler-internet-access', 'Zscaler', 'zscalerbyz', 'Zscaler Internet Access', '["BROWSER_PLUGIN","SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Internet Access candidate.'),
('zscaler-private-access', 'Zscaler', 'zscaler_private_access', 'Zscaler Private Access', '["SAML_2_0"]', 'saml_candidate', 'brand_variant', 'Private Access candidate.');
